apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: main
          image: ondrejsika/kcdczsk23-server
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          resources:
            requests:
              cpu: 30m
              memory: 20Mi
            limits:
              cpu: 60m
              memory: 40Mi
